"""Added index field to element table

Revision ID: 5614602f1a5d
Revises: aee93cf3d2f9
Create Date: 2024-05-21 18:17:54.412260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5614602f1a5d'
down_revision = 'aee93cf3d2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('element', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('element', schema=None) as batch_op:
        batch_op.drop_column('index')

    # ### end Alembic commands ###
