"""Added description to collection

Revision ID: aee93cf3d2f9
Revises: cb2e1dd36c45
Create Date: 2024-01-27 17:11:37.943237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee93cf3d2f9'
down_revision = 'cb2e1dd36c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_column('desc')

    # ### end Alembic commands ###
